export const baseUrl = process.env.BASE_URL ?? 'http://localhost:3000'
export const finchApiUrl = process.env.FINCH_API_URL ?? 'https://api.tryfinch.com'
export const sandboxApiUrl = process.env.FINCH_SANDBOX_URL ?? 'https://sandbox.tryfinch.com/api'
export const appName = process.env.APP_NAME ?? 'Acme Co.'
export const supportEmail = process.env.SUPPORT_EMAIL ?? 'developers@tryfinch.com'
